
# Build settings
remote_theme: mmistakes/minimal-mistakes@4.17.2

# Theme settings
url: "https://vestigl.com"
baseurl: "/"
minimal_mistakes_skin: "dark"

title: "Vestigl Creations"
title_separator: "-"
subtitle: "Software, Hardware, and Everything In Between"
description: "Programming, hardware, software, keyboards, games, controllers, and more. Come stop by and see what's cooking."
logo: "/assets/images/logo.png"
masthead_title: "Vestigl Creations"
words_per_minute: 180 # Make this slightly below average as there will be diagrams that will slow people down.

search: true
search_full_content: true
search_provider: "lunr"

# Post settings
permalink: /:categories/:title/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Author information
name: "Drew Mills"
author:
  name: "Drew Mills"
  avatar: "/assets/images/bio.jpg"
  bio: "Software and hardware engineer. Low-level languages, embedded systems, controllers, games, and more."
  location: "Houston, Texas, USA"
  email: "drew@vestigl.com"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VestiglDrew"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FranticRain"
    - label: "reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/Drewbadour/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/drew-mills-18326414b/"

# Collections
collections:
  xbox:
    output: true
    permalink: /:collection/:path

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _xbox
  - scope:
      path: ""
      type: xbox
    values:
      layout: single
      author_profile: false
      share: true
      sidebar:
        nav: "xbox"

# Github repository
repository: FranticRain/franticrain.github.io

# Plugin management/github pages whitelist
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages
